### ISSUE TITLE
Create Lite Design and all page Main Menu

### ISSUE THREAD

**Issue by popadiyk** [popadiyk/lavbul#10]
Створити дизайн основної сторінки
Створити пункти меню
Створити усі сторінки основоного меню

**Comment by VitaliyBogdanuk** [comment]
[pinkrio.zip](https://github.com/popadiyk/lavbul/files/1031290/pinkrio.zip)

викачайте архів розпакуйте і заходьте з індекса, там є багато цікавих речей можна стягнути лише те що нам піходить
