### ISSUE TITLE
Create DB Model in https://dbdesigner.net/

### ISSUE THREAD

**Issue by popadiyk** [popadiyk/lavbul#11]
Створити подібну ДБ модель до нашого сайту, 
Зареєструватись на https://dbdesigner.net/
Додати усіх, щоб кожен міг її редагувати
Згодом, коли створимо нашу модель в MySQL використання данного сайту буде не потрібним, а зараз - дуже зручна штука

**Comment by VitaliyBogdanuk** [comment]
що ти маєшь на увазі під "подібну" модель?
Я там зареєстрований і створював моделі, які таблиці мають бути? як їх необхідно звьязувати між собою? Потрібна вхідна інформація для створення моделі.

**Comment by popadiyk** [comment]
В мене є моделька яка має бути, я скину скрін сьогодні в це ішю

пятница, 26 мая 2017 г. пользователь VitaliyBogdanuk написал:

**Comment by popadiyk** [comment]
![image](https://cloud.githubusercontent.com/assets/23504381/26484240/a883eea2-41f9-11e7-9eae-c5793d9348d9.png)

Вибач за якість, покищо це, там ще дещо додасться, таблиця кріейтерів поки не потрібна

**Comment by VitaliyBogdanuk** [comment]
розтягни таблиці так щоб не було скролів всередині і я бачив усі елементи.
і також щоб не перекривались назви таблиць.
і якість дійсно трохи херова ) якщо можно трохи чіткіши сфоткати то перефоткай.
повідключай ці жовті полоски.

**Comment by popadiyk** [comment]
![db](https://cloud.githubusercontent.com/assets/23504381/26522240/a80a0d10-4304-11e7-9c8b-baf940ab37b6.png)

**Comment by VitaliyBogdanuk** [comment]
![db_shop](https://cloud.githubusercontent.com/assets/23727250/26532018/5368d7d6-43ff-11e7-8c9f-4d3ba4d72f00.png)
схема бази, чекаю на ваші коментарі, та пропозиції щодо змін
