### ISSUE TITLE
Create Manufacturer Model

### ISSUE THREAD

**Issue by popadiyk** [popadiyk/lavbul#12]
![image](https://cloud.githubusercontent.com/assets/23504381/26466130/439da054-4196-11e7-9851-e1b9b337342c.png)
Банківські реквізіти необовязкові поля SumaDebt (поле яке рахуватиме заборгованість перед постачальником у випадку якщо той реалізатор, в іншому нул)

**Comment by SheseR** [comment]
solve model Manufacture
