### ISSUE TITLE
Падає сайт при додаванні в корзину

### ISSUE THREAD

**Issue by popadiyk** [popadiyk/lavbul#171]
Проблема: Якщо клікати по корзинці (після додавання, коли іконка стала блакитною) в корзину додається ще один такий товар, коли товар закінчується на складі, падає сайт
Для відновлення роботи потрібно почистити куку
Є 3 варіанта: 
1) або по кліку на блакитну іконку відкривати корзину,  
2) поставити ліміт, щоб не додавало більше чим на складі
3) піся першого додавання робити її не клікабельну, а додати альт з надписом "Кількість данного товару можна редагувати у корзині"
![image](https://user-images.githubusercontent.com/23504381/29002100-7d1403f0-7aa3-11e7-9829-cf08ecb8ac4a.png)

**Comment by VitaliyBogdanuk** [comment]
Теперь кнопка реально дісаблед! )
