### ISSUE TITLE
Не спрацьовує іноді дропдаун на іконці юзер

### ISSUE THREAD

**Issue by popadiyk** [popadiyk/lavbul#173]
Помітив що перестає працювати дропдаун ІНФО та дропдаун Профіль після відкриття корзини

![image](https://user-images.githubusercontent.com/23504381/29003469-dca97cac-7abf-11e7-9d36-7465b888a464.png)

**Comment by VitaliyBogdanuk** [comment]
Труп валяється десь в скрипті корзини, після відкриття корзини перестають працювати абсолютно всі дропдауни а також пагінація на продуктах.

**Comment by VitaliyBogdanuk** [comment]
Не забувайте ставити ";" в скриптах =)

**Comment by popadiyk** [comment]
Якщо відкрити корзину і додати товар плюсиком, то перестає працювати :)
